PUT http://localhost:3001/person HTTP/1.1
content-type: application/json

{
  "id": 14,
  "name":"Abdallahabdallah",
  "vorname":"Mirelle",
  "benutzername":"fabianissam",
  "password":"fabianissam",
  "fachbereich": 5,
  "email":"fabian.abdallah98@googlemail.com"
}